# name = input("Enter your full name: ")
phone_number = input("Enter your phone number #: ")

# result = len(name)
# result = name.find("N")
# result = name.rfind("a")
# name = name.capitalize()
# name = name.upper()
# name = name.lower()
# result = name.isdigit()
# result = name.isalpha()
# phone_number = phone_number.count("-")
phone_number = phone_number.replace("-", "")

print(phone_number)